### ISSUE TITLE
Load data from Remote MySql into MemSQL

### ISSUE THREAD

**Issue by mubbashar** [memsql/memsql-loader#12]
Hi,
Thanks for the great tool :) . Is there any support to sync data from mysql database into Memsql database. I can not see it. Let me know
thanks!

**Comment by choochootrain** [comment]
hey @mubbashar, no problem! memsql-loader is great for csv files but is not a general purpose loading tool. are you looking for a tool for one time loading or for replication? we currently don't have a tool for replicating data from MySQL but for loading there are 2 solutions we offer:

* we have an [open source integration with Apache Spark](http://github.com/memsql/memsql-spark-connector) for more general purpose loading and transformation. you can use JDBC integration in Spark along with our connector's `saveToMemSQL` functionality to copy tables from MySQL to MemSQL.

* we have [MemSQL Streamliner](http://www.memsql.com/streamliner/), which is a product built on top of our Spark connector which also includes tools for importing data from MySQL, S3 and HDFS.

i hope that's helpful! I'm closing this issue for bookkeeping purposes but feel free to join our public slack group at chat.memsql.com if you have additional questions!
