### ISSUE TITLE
Last release is 2.0.4 created year ago - does it mean that current MemSQL is not supported ?

### ISSUE THREAD

**Issue by amorskoy** [memsql/memsql-loader#13]

**Comment by carlsverre** [comment]
This software is forwards compatible with MemSQL since it only takes dependency on primary spec like LOAD DATA.  So AFAIK it should be good to go with MemSQL 5.5 and beyond.

That said - if you encounter a specific bug please feel free to open a ticket so we can investigate.  Thanks :)

**Comment by amorskoy** [comment]
Thanks. I think nearest days I will try to use it with 5.5.
