### ISSUE TITLE
Commit hash in the help message for aspw installation is stale

### ISSUE THREAD

**Issue by priyankaiyer** [memsql/memsql-loader#19]
When we try to do 

` pip install \
        -e "git+git://github.com/rogerbinns/apsw.git@1be8f228f8b337f33f1a88ee55f61915133dd9b4#egg=apsw" \
        --global-option="fetch" --global-option="--sqlite" --global-option="--missing-checksum-ok" \
        --global-option="build" --global-option="--enable-all-extensions"`

It fails, since sqlite amalgamation has moved. We tried with 
` pip install \
        -e "git+git://github.com/rogerbinns/apsw.git@26b61c39a98db3ccad7f852adc944b0b8e94c242#egg=apsw" \
        --global-option="fetch" --global-option="--sqlite" --global-option="--missing-checksum-ok" \
        --global-option="build" --global-option="--enable-all-extensions"`

This works. Please check if the commit is compatible with the rest of the code.

**Comment by choochootrain** [comment]
thanks for catching this!
